steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jetsmx-pubsub-handler', '-f', 'infra/pubsub_handlers/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/jetsmx-pubsub-handler'

