#!/usr/bin/env python3
"""
Interactive script to set up .env file with all required credentials.
"""
import secrets
import base64
from pathlib import Path


def main():
    print("=" * 60)
    print("JetsMX Agent Framework - Environment Setup")
    print("=" * 60)
    print()
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Aborted.")
            return
    
    print("I'll help you create your .env file.")
    print("Press Enter to skip optional fields.")
    print()
    
    # Collect required values
    print("=" * 60)
    print("REQUIRED - Airtable Credentials")
    print("=" * 60)
    airtable_key = input("AIRTABLE_API_KEY (from https://airtable.com/create/tokens): ").strip()
    airtable_base = input("AIRTABLE_BASE_ID (from your base URL): ").strip()
    print()
    
    print("=" * 60)
    print("REQUIRED - Google Chat")
    print("=" * 60)
    chat_space = input("GOOGLE_CHAT_SPACE_ID (e.g., spaces/AAAAxxxxxxx): ").strip()
    print()
    
    print("=" * 60)
    print("REQUIRED - Google Drive Folders")
    print("=" * 60)
    print("Get folder IDs from URLs: https://drive.google.com/drive/folders/{FOLDER_ID}")
    resumes_folder = input("DRIVE_FOLDER_RESUMES_INCOMING: ").strip()
    probe_folder = input("DRIVE_FOLDER_TRANSCRIPTS_PROBE: ").strip()
    interview_folder = input("DRIVE_FOLDER_TRANSCRIPTS_INTERVIEW: ").strip()
    print()
    
    print("=" * 60)
    print("OPTIONAL - Additional Settings")
    print("=" * 60)
    gmail_email = input("GMAIL_USER_EMAIL [jobs@jetstreammx.com]: ").strip() or "jobs@jetstreammx.com"
    gcp_project = input("GCP_PROJECT_ID [jetsmx-agent]: ").strip() or "jetsmx-agent"
    environment = input("ENVIRONMENT [development]: ").strip() or "development"
    log_level = input("LOG_LEVEL [INFO]: ").strip() or "INFO"
    print()
    
    # Generate webhook secret
    print("Generating secure webhook secret...")
    webhook_secret = base64.b64encode(secrets.token_bytes(32)).decode('utf-8')
    print(f"Generated: {webhook_secret[:20]}...")
    print()
    
    # Create .env content
    env_content = f"""# ============================================
# JetsMX Agent Framework - Environment Variables
# ============================================
# Auto-generated by scripts/setup_env.py
# ============================================

# ------------------------------------------
# Google Cloud Platform
# ------------------------------------------
GCP_PROJECT_ID={gcp_project}
GCP_SERVICE_ACCOUNT_JSON_PATH=./google-service-account-keys.json

# ------------------------------------------
# Airtable Configuration
# ------------------------------------------
AIRTABLE_API_KEY={airtable_key}
AIRTABLE_BASE_ID={airtable_base}

# ------------------------------------------
# Gmail Configuration
# ------------------------------------------
GMAIL_USER_EMAIL={gmail_email}
GMAIL_WATCH_TOPIC=projects/{gcp_project}/topics/jetsmx-gmail-events

# ------------------------------------------
# Google Calendar
# ------------------------------------------
CALENDAR_ID=primary

# ------------------------------------------
# Google Chat
# ------------------------------------------
GOOGLE_CHAT_SPACE_ID={chat_space}

# ------------------------------------------
# Pub/Sub Topics
# ------------------------------------------
PUBSUB_TOPIC_AIRTABLE=jetsmx-airtable-events
PUBSUB_TOPIC_GMAIL=jetsmx-gmail-events
PUBSUB_TOPIC_DRIVE=jetsmx-drive-events
PUBSUB_TOPIC_CHAT=jetsmx-chat-events

# ------------------------------------------
# Google Drive Folders
# ------------------------------------------
DRIVE_FOLDER_RESUMES_INCOMING={resumes_folder}
DRIVE_FOLDER_TRANSCRIPTS_PROBE={probe_folder}
DRIVE_FOLDER_TRANSCRIPTS_INTERVIEW={interview_folder}

# ------------------------------------------
# Environment & Logging
# ------------------------------------------
ENVIRONMENT={environment}
LOG_LEVEL={log_level}

# ------------------------------------------
# Cloud Run (Webhooks)
# ------------------------------------------
WEBHOOK_SECRET={webhook_secret}

# ------------------------------------------
# Vertex AI
# ------------------------------------------
VERTEX_AI_LOCATION=us-central1
"""
    
    # Write .env file
    env_file.write_text(env_content)
    print("✅ Created .env file successfully!")
    print()
    
    # Validate
    print("=" * 60)
    print("Validation")
    print("=" * 60)
    
    missing = []
    if not airtable_key or airtable_key.startswith("YOUR_"):
        missing.append("AIRTABLE_API_KEY")
    if not airtable_base or airtable_base.startswith("YOUR_"):
        missing.append("AIRTABLE_BASE_ID")
    if not chat_space or chat_space.startswith("YOUR_"):
        missing.append("GOOGLE_CHAT_SPACE_ID")
    if not resumes_folder or resumes_folder.startswith("YOUR_"):
        missing.append("DRIVE_FOLDER_RESUMES_INCOMING")
    if not probe_folder or probe_folder.startswith("YOUR_"):
        missing.append("DRIVE_FOLDER_TRANSCRIPTS_PROBE")
    if not interview_folder or interview_folder.startswith("YOUR_"):
        missing.append("DRIVE_FOLDER_TRANSCRIPTS_INTERVIEW")
    
    if missing:
        print("⚠️  Warning: The following required fields are missing:")
        for field in missing:
            print(f"   - {field}")
        print()
        print("Please edit .env and fill in these values before deploying.")
    else:
        print("✅ All required fields are filled in!")
    
    print()
    print("=" * 60)
    print("Next Steps")
    print("=" * 60)
    print("1. Verify google-service-account-keys.json exists")
    print("2. Test configuration: python -c 'from shared.config.settings import get_settings; print(get_settings())'")
    print("3. Deploy infrastructure: python scripts/setup_pubsub.py")
    print("4. See NEXT_STEPS.md for full deployment guide")
    print()


if __name__ == "__main__":
    main()

